name: HerokuContainer
 
on:
  push:
    branches:
     - main
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build and deploy the Docker image
        env:
          HEROKU_API_KEY: ae96fa69-33ed-4084-92c6-a3561a5b8782
          APP_NAME: ${{ 'p40backend' }}
        run: |
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            heroku container:push web -a $APP_NAME
            heroku container:release web -a $APP_NAME